// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/crypto_pricing.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CryptoPricingClient is the client API for CryptoPricing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CryptoPricingClient interface {
	GetPrice(ctx context.Context, in *PriceRequest, opts ...grpc.CallOption) (*PriceResponse, error)
}

type cryptoPricingClient struct {
	cc grpc.ClientConnInterface
}

func NewCryptoPricingClient(cc grpc.ClientConnInterface) CryptoPricingClient {
	return &cryptoPricingClient{cc}
}

func (c *cryptoPricingClient) GetPrice(ctx context.Context, in *PriceRequest, opts ...grpc.CallOption) (*PriceResponse, error) {
	out := new(PriceResponse)
	err := c.cc.Invoke(ctx, "/crypto_pricing.CryptoPricing/GetPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CryptoPricingServer is the server API for CryptoPricing service.
// All implementations must embed UnimplementedCryptoPricingServer
// for forward compatibility
type CryptoPricingServer interface {
	GetPrice(context.Context, *PriceRequest) (*PriceResponse, error)
	mustEmbedUnimplementedCryptoPricingServer()
}

// UnimplementedCryptoPricingServer must be embedded to have forward compatible implementations.
type UnimplementedCryptoPricingServer struct {
}

func (UnimplementedCryptoPricingServer) GetPrice(context.Context, *PriceRequest) (*PriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrice not implemented")
}
func (UnimplementedCryptoPricingServer) mustEmbedUnimplementedCryptoPricingServer() {}

// UnsafeCryptoPricingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CryptoPricingServer will
// result in compilation errors.
type UnsafeCryptoPricingServer interface {
	mustEmbedUnimplementedCryptoPricingServer()
}

func RegisterCryptoPricingServer(s grpc.ServiceRegistrar, srv CryptoPricingServer) {
	s.RegisterService(&CryptoPricing_ServiceDesc, srv)
}

func _CryptoPricing_GetPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoPricingServer).GetPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crypto_pricing.CryptoPricing/GetPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoPricingServer).GetPrice(ctx, req.(*PriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CryptoPricing_ServiceDesc is the grpc.ServiceDesc for CryptoPricing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CryptoPricing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crypto_pricing.CryptoPricing",
	HandlerType: (*CryptoPricingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPrice",
			Handler:    _CryptoPricing_GetPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/crypto_pricing.proto",
}
